apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gopher-slack-bot
  namespace: gopher-slack-bot
  labels:
    app: gopher-slack-bot
    version: 810a0b285468265bf5a8486c051e641c61564b8f
  annotations:
    description: Gopher Slack Bot
spec:
  replicas: 1
  revisionHistoryLimit: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: gopher-slack-bot
      labels:
        app: gopher-slack-bot
      annotations:
        description: Gopher Slack Bot
    spec:
      containers:
      - name: gopher-slack-bot
        image: eu.gcr.io/gopher-slack-bot/bot:810a0b285468265bf5a8486c051e641c61564b8f
        ports:
         - name: healthz-port
           containerPort: 8081
           hostPort: 8081
        readinessProbe:
          httpGet:
            path: /healthz
            port: healthz-port
          initialDelaySeconds: 15
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz-port
          initialDelaySeconds: 15
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 400m
            memory: 150Mi
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /tmp/datastore.json
          - name: GOPHERS_SLACK_BOT_NAME
            valueFrom:
              secretKeyRef:
                name: gopher-secret
                key: botname
          - name: GOPHERS_SLACK_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: gopher-secret
                key: token
          - name: GOPHER_SLACK_BOT_TWITTER_CONSUMER_KEY
            valueFrom:
              secretKeyRef:
                name: gopher-twitter-secret
                key: consumerKey
          - name: GOPHER_SLACK_BOT_TWITTER_CONSUMER_SECRET
            valueFrom:
              secretKeyRef:
                name: gopher-twitter-secret
                key: consumerSecret
          - name: GOPHER_SLACK_BOT_TWITTER_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: gopher-twitter-secret
                key: accessToken
          - name: GOPHER_SLACK_BOT_TWITTER_ACCESS_TOKEN_SECRET
            valueFrom:
              secretKeyRef:
                name: gopher-twitter-secret
                key: accessTokenSecret
        volumeMounts:
          - name: datastore
            mountPath: /tmp
            readOnly: true
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      volumes:
        - name: datastore
          secret:
            secretName: gopher-datastore
            items:
              - key: file
                path: datastore.json
